version: 0.2
become: yes
phases:
  pre_build:
    commands:
      - echo "Install Hashicopr Packer"
      - curl -O https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip 
      - unzip -fo packer_*.zip
      - mv packer_* /usr/local/bin
      - mv /usr/local/bin/packer_* /usr/local/bin/packer
      - curl -qL -o jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ./jq
      - mv jq /usr/local/bin 
      - pwd
      - ls -lrt $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/hcl-packer/
      - packer fix buildspec_packer.yml
      - packer validate buildspec_packer.yml
  build:
    commands:
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json 
      - aws configure set region $AWS_REGION
      - ls -lrt $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/hcl-packer/
      - ls -lrt
      - packer build buildspec_packer.yml -debug
  post_build:
    commands:
      - echo "Packer Job is completed on `date`"
